### ISSUE TITLE
CSS Style Guide

### ISSUE THREAD

**Issue by jim-rosales** [tommygebru/bws-colmaracademy#2]
Your style sheet is very compressed! It is the most space and size efficient, short of being completely compressed to remove all spaces and line breaks. Your technique would require the least vertical and horizontal scrolling as you write and edit CSS but at the potential cost of increasing the difficulty in browsing and finding things you are looking for.

Take a look at this [style guide](https://github.com/airbnb/css) and analyze whether you'd want to adopt its guidelines as an alternative.

Some mentioned in the style guide, for example, are having one selector per line, having a space before the opening `{` and your properties should all be on new lines as shown below:
```CSS
section.campus-showcase .main-column {
  width: 60%;
  display:flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding: 32px 24px;
}

section.campus-showcase .main-column h1 {
  font-size: 1.85em; 
  font-weight: bold; 
  margin: 10px 0; 
  align-self: flex-start;
}

section.campus-showcase .main-column p {
  margin: 24px 0;
}

section.campus-showcase .main-column span {
  margin: 24px 0;
  align-self: flex-start;
}

section.campus-showcase .main-column img {
  width: 100%;
  height: auto;
}
``` 

It's up to you how you format your stylesheet so consider doing some more research in this area to decide which formatting standard suites your needs better. 

https://github.com/tommygebru/colmaracademy/blob/1f55ee45c3ee9f58e5cb147dcc2ff6bc25a0bb72/style.css#L55-L72
